spring:
  application:
    name: zuul-api-gateway-server
server:
  port: 8080
  tomcat:
    connection-timeout: 5000000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
zuul:
  routes:
    customer-application:
      url: http://localhost:8081
      path: /customer/**
    order-application:
      url: http://localhost:8082
      path: /order/**





